/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dogflesh (https://sketchfab.com/dogflesh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-9439cb5e09cc44caa63dfbfb299df45f
Title: Retro computer
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";
import { ENVIRONMENT } from "../constants/environment.const";

type GLTFResult = GLTF & {
	nodes: {
		Object_2: THREE.Mesh;
		Object_3: THREE.Mesh;
	};
	materials: {
		None: THREE.MeshStandardMaterial;
	};
};

export function Computer(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(`${ENVIRONMENT.workerBucketUrl}/models/pc.glb`) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
				<mesh name="Object_2" castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.None} />
				<mesh name="Object_3" castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.None} />
			</group>
		</group>
	);
}

useGLTF.preload("/models_pc.glb");
