/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sinner.chd (https://sketchfab.com/sinner.chd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fortnite-miles-morales-2eeed4f44ff64efda054b83325146842
Title: Fortnite-miles-morales
*/

import * as THREE from 'three'
import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ENVIRONMENT } from '../constants/environment.const'
import { useControls } from 'leva'

type GLTFResult = GLTF & {
    nodes: {
        Object_7: THREE.SkinnedMesh
        Object_8: THREE.SkinnedMesh
        Object_9: THREE.SkinnedMesh
        GLTF_created_0_rootJoint: THREE.Bone
    }
    materials: {
        M_MED_FearlessFlightHero_Body: THREE.MeshPhysicalMaterial
        DefaultMaterial: THREE.MeshPhysicalMaterial
        M_MED_FearlessFlightHero_FaceAcc: THREE.MeshPhysicalMaterial
    }
}

export function Miles(props: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group>(null)

    const { nodes, materials, animations } = useGLTF(`${ENVIRONMENT.workerBucketUrl}/models/miles.glb`) as GLTFResult
    const { actions, names } = useAnimations(animations, group)

    const { animationName } = useControls('Miles', {
        animationName: { value: "FearlessFlight_Male_idle", options: names },
    });

    useEffect(() => {
        actions[animationName]?.reset().fadeIn(0.5).play();

        return () => {
            actions[animationName]?.fadeOut(0.5);
        };
    }, [animationName]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="M_MED_FearlessFlightHero_LOD0ao_177">
                                <group name="GLTF_created_0">
                                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials.M_MED_FearlessFlightHero_Body}
                                        skeleton={nodes.Object_7.skeleton}
                                        castShadow
                                    />
                                    <skinnedMesh
                                        name="Object_8"
                                        geometry={nodes.Object_8.geometry}
                                        material={materials.DefaultMaterial}
                                        skeleton={nodes.Object_8.skeleton}
                                        castShadow
                                    />
                                    <skinnedMesh
                                        name="Object_9"
                                        geometry={nodes.Object_9.geometry}
                                        material={materials.M_MED_FearlessFlightHero_FaceAcc}
                                        skeleton={nodes.Object_9.skeleton}
                                        castShadow
                                    />
                                    <group name="M_MED_FearlessFlightHero_LOD0mo_176" />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/miles.glb')
